ALTER TABLE order_works ADD COLUMN IF NOT EXISTS is_confirmed BOOLEAN DEFAULT FALSE;
ALTER TABLE order_parts ADD COLUMN IF NOT EXISTS is_confirmed BOOLEAN DEFAULT FALSE;
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'Approved' AFTER 'Approval';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'Payment' AFTER 'Ready';
